name: tickets
version: 0.0.1
description: A ticket Commerce Application
author: Paul Matencio paulo.matencio@gmail.com
homepage: <my url>
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
#server dependencies
  json_object: '1.0.19+1'
  mongo_dart: '0.2.5+1'
  resource: '^1.1.0'
  guinness: '<= 0.1.18'
  connection_pool: '0.1.0+2'
  dartson: '0.2.5'
  shelf: '>=0.6.5 <0.7.0'
  shelf_static: '0.2.3+3'
  shelf_route: '0.14.1'
  shelf_path: '0.1.7'
  unittest: '<= 0.12.4'
#client dependencies
  bootjack: "0.6.5"
  browser: "0.10.0+2"
  sass: "0.4.2"
transformers:
- dartson
- sass:
    executable: sassc